#!/usr/bin/env bash
#A simple script that accepts a string as an argument and checks if the IP adress is on the network

if [ -z "$1" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit
fi

ping "$1" -c 5